// for (const key in response.data.queryresult.pods) {
        //   // if (res[key].scanner == "Identity" && res[key].title == "Input interpretation" ) {
        //   //   queryOut1 = res[key].subpods[0].plaintext      
        //   //   console.log(queryOut1);      
        //   // }
        //   // if (res[key].scanner == "Solve" && res[key].title == "Results" ) {
        //   //   let item = res[key].subpods
        //   //   item.forEach(element => {
        //   //     if(element.title == ""){
        //   //       queryOut2 = queryOut2 + element.plaintext + ", ";
        //   //     }
        //   //   });
        //   //   console.log(queryOut2);
        //   // }

        //   let item = res[key].subpods
        //     item.forEach(element => {
        //       if(element.title == ""){
        //         // queryOut2 = queryOut2 + element.plaintext + ", ";
        //         console.log(element.plaintext);
        //         query.push(element.plaintext)
        //       }
        //     });
        //     // console.log(queryOut2);

        // }
        // for (let index = 0; index < query.length; index++) {
        //   const element = query[index];
        //   console.log(element)
        // }
        // setQuery([])